export enum CancellationPolicyPenalty {
    RESERVATION_PERCENTAGE = 'RESERVATION_PERCENTAGE',
    FULL_DAILIES_PERCENTAGE = 'FULL_DAILIES_PERCENTAGE',
    FIRST_NIGHT_AMOUNT = 'FIRST_NIGHT_AMOUNT',
}
