export enum ReservationDepositType {
    PERCENTAGE_ON_RESERVATION = 'PERCENTAGE_ON_RESERVATION',
    FULL_AMOUNT_ON_RESERVATION = 'FULL_AMOUNT_ON_RESERVATION',
    DAYLIES_FULL_AMOUNT_ON_RESERVATION = 'DAYLIES_FULL_AMOUNT_ON_RESERVATION',
    FIRST_DAYLY_ON_RESERVATION = 'FIRST_DAYLY_ON_RESERVATION',
    NO_CHARGE = 'NO_CHARGE',
}
