export enum UnavailableSource {
    HOSTING_RULES = 'HOSTING_RULES',
    SEASON_RULES = 'SEASON_RULES',
    SPECIAL_DATES = 'SPECIAL_DATES',
    OFFERS = 'OFFERS',
    RESERVATION = 'RESERVATION',
}

export enum UnavailabilityReason {
    MIN_DAYS_NOT_REACHED = 'MIN_DAYS_NOT_REACHED',
    ALL_ROOMS_OCCUPIED = 'ALL_ROOMS_OCCUPIED',
    WEEKDAY_NOT_AVAILABLE = 'WEEKDAY_NOT_AVAILABLE',
    MAX_GUESTS_EXCEEDED = 'MAX_GUESTS_EXCEEDED',
    MAX_CHILDREN_EXCEEDED = 'MAX_CHILDREN_EXCEEDED',
}
